[package]
name = "neko2p"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
clap = { version = "4.5.26", features = ["derive"] }
common = { path = "common" }
rustls = "0.23.21"
rustls-pki-types = "1.10.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_yaml_ng = "0.10.0"
tokio = { version = "1.43.0", features = ["full"] }
tokio-rustls = "0.26.1"
uuid = { version = "1.12.0", features = ["v4"] }
webpki-roots = "0.26.7"

# protocols
hysteria2 = { path = "protocols/hysteria2" }
shadowsocks = { path = "protocols/shadowsocks" }
socks5 = { path = "protocols/socks5" }
trojan = { path = "protocols/trojan" }
vless = { path = "protocols/vless" }

dns = { path = "dns" }
