[package]
name = "neko2p"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
common = { path = "common" }
rustls = "0.23.20"
serde = { version = "1.0.216", features = ["derive"] }
serde_yaml_ng = "0.10.0"
tokio = { version = "1.42.0", features = ["full"] }
uuid = { version = "1.11.0", features = ["v4"] }

# protocols
#hysteria2 = { path = "protocols/hysteria2" }
shadowsocks = { path = "protocols/shadowsocks" }
socks5 = { path = "protocols/socks5" }
trojan = { path = "protocols/trojan" }
vless = { path = "protocols/vless" }
