[package]
name = "trojan"
version = "0.1.0"
edition = "2021"
description = "trojan protocol implementation"

[dependencies]
common = { path = "../../common" }
rustls-pki-types = "1.10.1"
sha2 = "0.10.8"
tokio = { version = "1.42.0", features = ["io-util", "net"] }
tokio-rustls = "0.26.1"
webpki-roots = "0.26.7"
