[package]
name = "vless"
version = "0.1.0"
edition = "2021"
description = "vless protocol implementation"

[dependencies]
bytes = "1.9.0"
common = { path = "../../common" }
tokio = { version = "1.43.0", features = ["net", "io-util"] }
uuid = "1.11.1"
